[package]
name = "lynnlei"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ammonia = "3.3.0"
glob = "0.3.1"
maud = "0.26.0"
pulldown-cmark = "0.10.0"
